#!/bin/bash

export TF_VAR_tenancy_ocid=PROVIDETenancyOcId
export TF_VAR_user_ocid=PROVIDEUserOcId
export TF_VAR_fingerprint=PROVIDEFingerprint
export TF_VAR_region=PROVIDERegion
export TF_VAR_private_key_path=PROVIDEPrivateKeyPath
export TF_VAR_private_key_password=PROVIDEPrivateKeyPassword
export TF_VAR_compartment_ocid=PROVIDECompartmentOCID
